version: "2.1"

volumes:
  docker:

services:
  docker-container:
    build: .
    privileged: true
    pid: host
    network_mode: host
    ipc: host
    volumes:
      - docker:/var/lib/docker
    tmpfs:
      - /tmp
      - /var/log
